package com.example.theme.api

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class DSColorScheme(
    val main: Color,
    val onMain: Color,
    val onMainSecondary: Color,
    val onMainDisabled: Color,
    val onMainLight: Color,
    val onMainExtraLight: Color,
    val accent: Color,
    val onAccent: Color,
    val onAccentSecondary: Color,
    val onAccentDisabled: Color,
    val onAccentLight: Color,
    val onAccentExtraLight: Color,
    val accentHighContrast: Color,
    val background: Color,
    val onBackground: Color,
    val onBackgroundSecondary: Color,
    val onBackgroundDisabled: Color,
    val onBackgroundLight: Color,
    val onBackgroundExtraLight: Color,
    val surface: Color,
    val onSurface: Color,
    val onSurfaceSecondary: Color,
    val onSurfaceDisabled: Color,
    val onSurfaceLight: Color,
    val onSurfaceExtraLight: Color,
    val premium: Color,
    val onPremium: Color,
    val onPremiumSecondary: Color,
    val onPremiumDisabled: Color,
    val onPremiumLight: Color,
    val onPremiumExtraLight: Color,
    val critical: Color,
    val onCritical: Color,
    val onCriticalSecondary: Color,
    val onCriticalDisabled: Color,
    val onCriticalLight: Color,
    val onCriticalExtraLight: Color,
    val attention: Color,
    val onAttention: Color,
    val onAttentionSecondary: Color,
    val onAttentionDisabled: Color,
    val onAttentionLight: Color,
    val onAttentionExtraLight: Color,
    val success: Color,
    val onSuccess: Color,
    val onSuccessSecondary: Color,
    val onSuccessDisabled: Color,
    val onSuccessLight: Color,
    val onSuccessExtraLight: Color,
    val brand: Color,
    val onBrand: Color,
    val onBrandSecondary: Color,
    val onBrandDisabled: Color,
    val onBrandLight: Color,
    val onBrandExtraLight: Color,
    val brand1: Color,
    val onBrand1: Color,
    val onBrand1Secondary: Color,
    val onBrand1Disabled: Color,
    val onBrand1Light: Color,
    val onBrand1ExtraLight: Color
)