package com.example.theme.impl.safepath

import androidx.compose.ui.graphics.Color
import com.example.theme.api.DSColorScheme

internal val dsColorSchemeSafePath = DSColorScheme(
    main = Color(0xFF5B667C),
    onMain = Color(0xFFFFFFFF),
    onMainSecondary = Color(0xFFFFFFBF),
    onMainDisabled = Color(0xFFFFFF80),
    onMainLight = Color(0xFFFFFF26),
    onMainExtraLight = Color(0xFFFFFF14),
    accent = Color(0xFF29AB87),
    onAccent = Color(0xFFFFFFFF),
    onAccentSecondary = Color(0xFFFFFFD9),
    onAccentDisabled = Color(0xFFFFFFA6),
    onAccentLight = Color(0xFFFFFF3D),
    onAccentExtraLight = Color(0xFFFFFF1F),
    accentHighContrast = Color(0xFF0F8564),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF000000),
    onBackgroundSecondary = Color(0xFF5B667C),
    onBackgroundDisabled = Color(0xFF8F99AB),
    onBackgroundLight = Color(0xFFDCDEE2),
    onBackgroundExtraLight = Color(0xFFF8F8F8),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF000000),
    onSurfaceSecondary = Color(0xFF5B667C),
    onSurfaceDisabled = Color(0xFF8F99AB),
    onSurfaceLight = Color(0xFFDCDEE2),
    onSurfaceExtraLight = Color(0xFFF8F8F8),
    premium = Color(0xFF276AE8),
    onPremium = Color(0xFFFFFFFF),
    onPremiumSecondary = Color(0xFFFFFFBF),
    onPremiumDisabled = Color(0xFFFFFF80),
    onPremiumLight = Color(0xFFFFFF33),
    onPremiumExtraLight = Color(0xFFFFFF1A),
    critical = Color(0xFFB72026),
    onCritical = Color(0xFFFFFFFF),
    onCriticalSecondary = Color(0xFFFFFFBF),
    onCriticalDisabled = Color(0xFFFFFF80),
    onCriticalLight = Color(0xFFFFFF33),
    onCriticalExtraLight = Color(0xFFFFFF1A),
    attention = Color(0xFFFFDA6D),
    onAttention = Color(0xFF04121A),
    onAttentionSecondary = Color(0x04121ABF),
    onAttentionDisabled = Color(0x04121A80),
    onAttentionLight = Color(0x04121A33),
    onAttentionExtraLight = Color(0x04121A1A),
    success = Color(0xFF669900),
    onSuccess = Color(0xFFFFFFFF),
    onSuccessSecondary = Color(0xFFFFFFBF),
    onSuccessDisabled = Color(0xFFFFFF80),
    onSuccessLight = Color(0xFFFFFF33),
    onSuccessExtraLight = Color(0xFFFFFF1A),
    brand = Color(0xFFF1602F),
    onBrand = Color(0xFFFFFFFF),
    onBrandSecondary = Color(0xFFFFFFBF),
    onBrandDisabled = Color(0xFFFFFF80),
    onBrandLight = Color(0xFFFFFF33),
    onBrandExtraLight = Color(0xFFFFFF1A),
    brand1 = Color(0xFF8BCEE2),
    onBrand1 = Color(0xFF000000),
    onBrand1Secondary = Color(0x000000BF),
    onBrand1Disabled = Color(0x00000080),
    onBrand1Light = Color(0x00000033),
    onBrand1ExtraLight = Color(0x0000001A)
)